function Config = configLoad(varargin)
%CONFIGLOAD Desay FACF 复现参数；每窗严格使用固定数量的连续数据包。
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
Config = struct('path_data',fullfile(root,'data'), ...
    'path_res',fullfile(root,'results'), 'parser_path','', ...
    'window_packets',20, 'step_packets',20, ...
    'pair_min_distance',3, 'acf_shift',1, ...
    'amplitude_compensation','paper_normalization', ...
    'stream_aggregation','mean', 'rx_indices',[], ...
    'threshold',NaN, 'threshold_profile','', 'smooth_windows',3, 'make_plots',true, ...
    'show_figures',true, ...
    'file_pattern','*.csi','packet_formats',3,'source_mac','');
assert(mod(numel(varargin),2)==0,'RapidPD:Config','参数必须成对出现。');
for k=1:2:numel(varargin)
    key=char(varargin{k});
    assert(isfield(Config,key),'RapidPD:Config','未知参数: %s',key);
    Config.(key)=varargin{k+1};
end
validateattributes(Config.window_packets,{'numeric'},{'scalar','integer','>=',4});
validateattributes(Config.step_packets,{'numeric'},{'scalar','integer','positive'});
validateattributes(Config.pair_min_distance,{'numeric'},{'scalar','integer','>=',1});
assert(Config.pair_min_distance<Config.window_packets,'RapidPD:Config', ...
    'pair_min_distance 必须小于 window_packets。');
validateattributes(Config.acf_shift,{'numeric'},{'scalar','integer','positive'});
validateattributes(Config.smooth_windows,{'numeric'},{'scalar','integer','positive'});
assert(mod(Config.smooth_windows,2)==1,'RapidPD:Config','投票窗口数必须为奇数。');
assert(isscalar(Config.threshold) && (isnan(Config.threshold)||isfinite(Config.threshold)), ...
    'RapidPD:Config','threshold 必须是有限标量或 NaN。');
assert(string(Config.amplitude_compensation)=="paper_normalization", ...
    'RapidPD:Config','AX210 当前仅支持 paper_normalization：逐包子载波幅值和归一化。');
assert(ismember(string(Config.stream_aggregation),["mean","sum"]),'RapidPD:Config','stream_aggregation 无效。');
if ~isempty(Config.rx_indices)
    validateattributes(Config.rx_indices,{'numeric'},{'vector','integer','positive','finite'});
    assert(numel(unique(Config.rx_indices))==numel(Config.rx_indices), ...
        'RapidPD:Config','rx_indices 不能包含重复接收链。');
end
end
